-------------------------------------------------------------------------------
Test set: models.EndangeredAnimalTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 2.908 sec <<< FAILURE! - in models.EndangeredAnimalTest
all_returnsAllInstancesOfEndangeredAnimal_true(models.EndangeredAnimalTest)  Time elapsed: 0.754 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.all_returnsAllInstancesOfEndangeredAnimal_true(EndangeredAnimalTest.java:30)

update_updatesAgeAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.513 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.update_updatesAgeAttribute_true(EndangeredAnimalTest.java:57)

save_assignsIdAndSavesObjectToDatabase(models.EndangeredAnimalTest)  Time elapsed: 0.541 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.save_assignsIdAndSavesObjectToDatabase(EndangeredAnimalTest.java:22)

find_returnsAnimalWithSameId_secondAnimal(models.EndangeredAnimalTest)  Time elapsed: 0.524 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.find_returnsAnimalWithSameId_secondAnimal(EndangeredAnimalTest.java:40)

update_updatesHealthAttribute_true(models.EndangeredAnimalTest)  Time elapsed: 0.49 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "196.107.113.91", user "pcfuribhbzhumr", database "d6h28pq7taeg2l", SSL off
	at models.EndangeredAnimalTest.update_updatesHealthAttribute_true(EndangeredAnimalTest.java:49)

